### ISSUE TITLE
Initial code review

### ISSUE THREAD

**Issue by taylorreiter** [Arcadia-Science/nucleoside-finder#1]
* `README.md`: 
    * is the comma here intentional? "LC-MS/,MS" 
    * can you put the file names in single back ticks "`" so they stand out more?
    * Do you have the DOI link or url to zenodo yet?
* `nucleosidefinder6.ipynb`
    * Can you add a markdown cell to the top of the notebook stating what the notebook does?
    * Can you add versions to the notebook, or a yaml with the conda environment you used with all of the software versions?
    * you shouldn't need to establish the rootdir, as jupyter notebook will assume its the git repo if you start the notebook in this folder. Removing that will  make it easier for others to pick up this notebook and use it
    * Otherwise, this is a really pretty notebook and was really easy to read and follow!

**Comment by borgesadair1** [comment]
Thanks Taylor! I updated the `README.md` file with your suggestions. I also updated the jupyter notebook. What versions would you suggest adding to the notebook? The python versions? I can generate a yaml file for the conda env that runs my jupyter notebook, is that what you want?

**Comment by taylorreiter** [comment]
Yes a yaml file with the conda env that runs the jupyter notebook is exactly what I'm looking for. The readme looks great now!

**Comment by borgesadair1** [comment]
Added the yaml. if it all looks good to you I will close this issue!

**Comment by taylorreiter** [comment]
The yaml looks great, thanks Adair!
