### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mertcelebi** [Arcadia-Science/nucleoside-finder#2]
## Intro

Overall, this was pretty easy to review and the code was well documented. Thank you for putting the time creating individual functions and avoiding code duplication, that was great 🎉 ! Below are some comments and most of them are minor [nits](https://www.techopedia.com/definition/31651/nit). I don't think there are many deal-breakers down there, so feel free to take it or leave it. But there's definitely room for improvement :) 

### Structure/Documentation

- If not a big hassle, I'd rename the repo to `nucleoside-finder` for consistency across Arcadia repos.
- Directory structure could be improved. Overall it's a straightforward repository, but it'd be good to separate some of the inputs and outputs/results in designated folders to make the navigation a little easier and more visually intuitive.
- Nit: Probably worth using similar case for each file. You seem to use snake case mostly, which is good. But I'd prefer them to be all consistent. ie `Mass_lists_Nucleosides.csv` -> `mass_lists_nucleosides.csv`. If you rename files, don't forget to update the scripts that use/generate them.
- I'd add a `LICENSE` file with an MIT license (or the relevant license)

### Conda

- The `env.yml` file has very specific versions which may seem like a good thing on paper but it has several problems. You probably created this with `conda env export` or the equivalent, and this actually does a full dump of your environment with all the underlying packages. All good until now. The problem is the `ha654fa7_0` like sections at the end of each line. These generally encode the package version on a specific OS. So if you developed on MacOS (likely), this environment will not work on Linux. You could try `conda env export --from-history` to only export the packages that you explicitly installed to see if that produces something accurate AND manageable. In the worst case, this is fine and you can leave as is but you should document the specific OS you developed on.

### `README.md`

- I'd make your and Peter's names links to your GitHub or any other social profiles.
- If you adjust the the directory structure, you may want to spell it out here and potentially link to the relevant files explicitly.
- At a base minimum, I'd include on which OS/platform the software was developed and ran.
- Will this be linked to Binder or smth? If so, I'd make sure it runs start to finish.
- I'd definitely add instructions to the conda environment creation and activation and that the package versions are specified there.

### The Jupyter notebook

- There are some diagnostic code/outputs like `start = time.time()`, `print(end-start)` etc. I'd remove these, unless they serve a purpose for the end product. If you remove these, don't forget to remove the `time` import.
- Nit: since this is a Python Jupyter notebook, function names should use snake case.
- Nit: Clean-up unusused cells in the Jupyter notebook (towards the end) and unnecessary spaces.
- I was confused about where and how the .mgf files came from. I'd add a note at the top of the Jupyter notebook re-iterating where these files come from (I know you mention it in the README) and how to download them if there's a set of commands to run when downloading them. Example, the beginning of Ryan's pub code: https://github.com/Arcadia-Science/comparative-amoeboid-crawling/blob/main/03_notebooks/notebook_1_data_shape_components_and_iterative_window_search.ipynb
- Love the usage of the functions in the Jupyter notebook. Some questions/suggestions:
  - Why does the function `find_Nucleosides_From_MS2` have lines like `intensity_percent_cutoff = intens_cutoff1` or `mass_tolerance1 = ppm_tolerance1` since these values are inputs? Why not name them in detail in the first place and add the documentation about what the variables do to the function description?
  - The variable names are not very undescriptive for some of the lines. Lots of usage of `temp_` etc. Not a big deal obviously. In some cases, these can be eliminated. There are a lot of cases where you do something like `temp1 = X; df.append(temp1)` etc. These are mostly trivial, but in the `assign_Nucleotides_to_Masses` function, the usage of `item1`, `item2` etc is so confusing because of the nature of the loop.
  - Definitely not needed to address now, but if you want to improve the code, I'd divide the `find_Nucleosides_From_MS2` function into two functions. One that takes the raw file and returns a raw df. And the other takes the raw df and returns a summary df. It'd simplify both and make them quite manageable in length.
  - I assume most of the CSVs are pretty short and sweet, so probably not useful to address. But you do read the file twice technically and you can technically combine the file open call with the processing code.
- Definitely not needed right now, BUT. In the `list and process .mgf` section, for the `filename_corresponding_sample_list` variable, I'd use a dictionary in the future. You can do something like `filename_corresponding_sample_list = {'ORB59709': 'SP01','ORB59710': 'T4'}`. This would simplify the `filename_list` to `filename_list = filename_corresponding_sample_list.keys()` and the whole last part of that section to `filename_to_sample_column1.append(filename_corresponding_sample_list[row1.filename])` etc etc. Again not a big deal right now, but if the CSVs were big in size, the code would run much snappier.

**Comment by borgesadair1** [comment]
thanks mert! i have updated the repo accordingly.
